// ─── DATA ASSEMBLER ──────────────────────────────────────────────────────────
// This file combines all data sources into a single DATA export.
// Do NOT edit this file directly.
//
// To make changes:
//   • Personal info / skills / work / education → src/data/profile.tsx
//   • Projects                                  → src/data/projects.tsx
//   • Hackathons                                → src/data/hackathons.tsx
//   • Blog posts                                → content/*.mdx
// ─────────────────────────────────────────────────────────────────────────────

import { PROFILE } from "./profile";
import { PROJECTS } from "./projects";
import { HACKATHONS } from "./hackathons";

export const DATA = {
  ...PROFILE,
  projects: PROJECTS,
  hackathons: HACKATHONS,
} as const;
